### ISSUE TITLE
Swift package manager support (SPM)

### ISSUE THREAD

**Issue by jeffblake** [appspector/ios-sdk#11]
I don't use Cocoapods or Carthage - it would be great to add support for SPM :)

**Comment by valexa** [comment]
It should be at least a option !

**Comment by deszip** [comment]
Proposal for binary support in SPM was included in Swift 5.3 3 days ago:
https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md

We'll take a look at it and if it really works - definitely add support.

**Comment by mattmaddux** [comment]
Just to refresh this issue, here's the WWDC 2020 video on binary dependencies in SPM: https://developer.apple.com/videos/play/wwdc2020/10147/

Looks like it will require the xcframework format.

**Comment by geertbeskers** [comment]
SPM support should be really great! We also don't use carthage anymore since xcode12.

**Comment by sthwicked** [comment]
Assets (xcframeworks) are missing from 1.3.6 release and also Package.swift urls are malformed in binary targets?

**Comment by deszip** [comment]
We are in process of CI setup for SPM deploy. Should work fine by the end of the week.
btw, what do you mean by malformed urls? Which ones?

**Comment by sthwicked** [comment]
Cool! thanx 
Maybe I'm missing something but is "https://**github.com///releases/**download/1.3.6/AppSpectorSDK.xcframework.zip" a qualified url link?

**Comment by deszip** [comment]
Yeah, you're right, it's broken. We are fixing the deploy now, I think on Monday we'll have SPM working.

**Comment by deszip** [comment]
Ok guys, looks like it finally works:

![Снимок экрана 2020-11-11 в 21 07 35](https://user-images.githubusercontent.com/432462/98854694-8fed7c00-2463-11eb-92de-753f4b8d0991.png)

We appreciate your patience and help.

Updated docs: https://github.com/appspector/ios-sdk/blob/master/README.md#spm

**Comment by deszip** [comment]
Install with SPM is available for iOS/tvOS SDKs without E2EE support.
Encryption-enabled SDK will be available via SPM later, some reps should be ready for SPM.

Closing this, feel free to reopen if smith goes wrong with SPM support or you'll have any questions.
