### ISSUE TITLE
 Do I need to manually remove Appspector related code when deploying to the App Store?

### ISSUE THREAD

**Issue by azeek** [appspector/ios-sdk#14]
On Android, I was able to remove it at deployment by adding com.appspector:android-sdk-noop to Gradle.

How does ios do this?

There is no guide for this.

**Comment by deszip** [comment]
Hi @azeek, thanks for your question. The only automatic way to exclude SDK from AppStore builds is to have a separate target for this. Unfortunately there is no no-op version for iOS.

Also notice that SDK disables itself if it detects AppStore environment so even sending build with SDK to the review you'll not get sessions from real users.

**Comment by deszip** [comment]
Closing this, ping us if you have any questions here or in our slack: https://slack.appspector.com/
