### ISSUE TITLE
themis liberary not loaded error on app launch

### ISSUE THREAD

**Issue by archana211** [appspector/ios-sdk#16]
I am using cocoapods 1.10.0 , AppSpectorSDKE2E- 1.3.5 and themis -0.13.4 on app launch getting "Library not loaded" error for themis but app works fine if i use  cocoapods 1.9.3 , AppSpectorSDKE2E- 1.3.5 and themis -0.13.3.

Error: 
dyld: Library not loaded: @rpath/themis.framework/themis
 Referenced from: ~/Frameworks/AppSpectorSDKE2E.framework/AppSpectorSDKE2E
 Reason: image not found

**Comment by deszip** [comment]
Thanks for reporting.
How do you get different themis versions for the same AppSpector SDK version?
Can you please show your podfile?

**Comment by archana211** [comment]
Thanks for quick response.
I have not specify version in podfile  simply use,
pod 'AppSpectorSDKE2E'
But I guess themis framework made update from 0.13.3 to 0.13.4 , can you please verify ?

**Comment by deszip** [comment]
Yep you are right, themis 0.13.4 is static now, we discussed this issue with maintainers (they also respond quickly :)) and in 0.13.5 this will be fixed.
So now you have next options:
- wait for themis 0.13.5 available in cocapods trunk, I think a couple of days
- add to your podfile themis 0.13.3 which should override dependency

I'll keep this issue opened until themis 0.13.5 will be released so feel free to ping me here if you have any questions.

**Comment by archana211** [comment]
Okay, Thanks for the update.

**Comment by deszip** [comment]
We updated to themis v0.13.6 which addresses the issue. Could you please try AppSpector v1.4.0?

**Comment by deszip** [comment]
This should be fixed in version 1.4.0
Closing the issue, feel free to reopen it if you still have it.
