### ISSUE TITLE
Building ADHOC/enterprise build with fastlane leads to errors

### ISSUE THREAD

**Issue by katsumoto** [appspector/ios-sdk#17]
This occours since the last pod update to version 1.3.7.

Any ideas?

Console output:
` xcodebuild -exportArchive -exportOptionsPlist /var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/gym_config20201123-57298-xcz5d0.plist -archivePath '/Users/katsumoto/Library/Developer/Xcode/Archives/2020-11-23/IOM_beta 2020-11-23 17.38.05.xcarchive' -exportPath /var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/gym_output20201123-57298-15185kr
2020-11-23 17:39:00.024 xcodebuild[59646:3201780] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/MerchantBETA_2020-11-23_17-39-00.023.xcdistributionlogs'.
error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode_RC.app/Contents/Developer/usr/bin/python3 /Applications/Xcode_RC.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode_RC.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode_RC.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk -o /var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/ipatool20201123-59649-3e037h/thinned-out/armv7/Payload/ParcellyMerchantBeta.app/Frameworks/AppSpectorSDK.framework/AppSpectorSDK --generate-dsym /var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/ipatool20201123-59649-3e037h/thinned-out/armv7/Payload/ParcellyMerchantBeta.app/Frameworks/AppSpectorSDK.framework/AppSpectorSDK.dSYM --strip-swift-symbols /var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/ipatool20201123-59649-3e037h/thinned-in/armv7/Payload/ParcellyMerchantBeta.app/Frameworks/AppSpectorSDK.framework/AppSpectorSDK
Status: pid 59877 exit 1
Stdout:
    SDK path: /Applications/Xcode_RC.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk
    SDK version: 14.2
    PATH: ['/Applications/Xcode_RC.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode_RC.app/Contents/Developer/usr/bin']
    Using: /Applications/Xcode_RC.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
    MachoInfo: cd /
     ['/Applications/Xcode_RC.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo', '-info', '/var/folders/8c/qsrsp2kj2d1b3jy8xhn92l6r0000gn/T/ipatool20201123-59649-3e037h/thinned-in/armv7/Payload/ParcellyMerchantBeta.app/Frameworks/AppSpectorSDK.framework/AppSpectorSDK']
`

**Comment by deszip** [comment]
Hi, thanks for reporting. Can you please try with version 1.4.0 ?

**Comment by deszip** [comment]
@katsumoto closing this, feel free to reopen in case it still persists on the latest version.
