### ISSUE TITLE
Unable to add SPM dependency

### ISSUE THREAD

**Issue by sthwicked** [appspector/ios-sdk#18]
Afer a long wait on `Resolving ios-sdk` I get a `404 resource not found` error

Same error on versions 1.4.0, 1.3.7 and 1.3.6

**Comment by deszip** [comment]
Thanks for reporting, we are looking into it.
Looks like Xcode cant get correct URL for some reason if it's hosted on GitHub.

**Comment by deszip** [comment]
Could you please try with this URL: https://github.com/appspector/ios-sdk-spm?

**Comment by sthwicked** [comment]
Yeah, this seems to work just fine

**Comment by deszip** [comment]
Awesome, thanks for finding this out.
