### ISSUE TITLE
`isRunning` return false

### ISSUE THREAD

**Issue by aShaforostov** [appspector/ios-sdk#20]
Hello)

I want manually start and stop SDK `AppSpectorSDK 1.3.3`

After I call `AppSpector.run(with: config)` i want know that sdk is running
But if i call `AppSpector.isRunning()` it's return false

`AppSpector.isRunning()` returns true only if i call `run` at start of application

**Comment by deszip** [comment]
Hi @aShaforostov , thanks for reporting, we'll take a look and get back to you.
Meanwhile, can you please check with the latest SDK version?
