### ISSUE TITLE
App not responding if logs monitor enabled.

### ISSUE THREAD

**Issue by pradyumna67** [appspector/ios-sdk#22]
If I enable Monitor.logs, after click on some particular buttons app is not responding. Except logs remaining are working fine.
Tested on iPhone 5s and 11 pro.

**Comment by deszip** [comment]
Hi @pradyumna67 , thanks for reporting this. Can you pls pause app in debugger when this happens and show me call stacks pls?

**Comment by deszip** [comment]
Version 1.4.6 includes potential fix for this issue. Closing this, feel free to reopen is issue still persists.
