### ISSUE TITLE
AppSpectorSDK via CocoaPods arm64

### ISSUE THREAD

**Issue by Lukasz2891** [appspector/ios-sdk#25]
I'd like to use AppSpectorSDK on arm64-based device using a CocoaPods installation. Now the podspec file contains excluding build for that architecture.

**Comment by deszip** [comment]
We'll take a look, thanks for reporting

**Comment by deszip** [comment]
@Lukasz2891 check please v1.4.10, this should be fixed in this release.

**Comment by deszip** [comment]
Closing this, feel free to reopen if issue persists.

**Comment by Lukasz2891** [comment]
I took 3 years. I’m not even working as a mobile dev now.
