### ISSUE TITLE
Performance mode is always active

### ISSUE THREAD

**Issue by mobileTrilix** [appspector/ios-sdk#27]
Hello,
I encountered one issue with your library, in configuration I added four monitors that I need (http, logs, sqlite and userDefaults). Every time appspector starts it turns on these 4 monitors and performance monitor alongside them. I do not want to run performance monitor because I don't need it and it consumes a lot of data. This is the exact code I use in my application: 
`let appSpectorConfig = AppSpectorConfig(apiKey: "ios_.................................", monitorIDs: [Monitor.http, Monitor.logs,Monitor.sqlite, Monitor.userdefaults])
            AppSpector.run(with: appSpectorConfig!)`
Please check if there is some issue with performance mode or am I doing something wrong? I am looking forward to hearing from you.

**Comment by deszip** [comment]
Hi @mobileTrilix , thanks for reporting this. Issue is already fixed and will be included in the next SDK release.

**Comment by deszip** [comment]
@mobileTrilix please check v1.4.10, it includes fix for this.

**Comment by deszip** [comment]
Closing this, feel free to reopen if issue persists.
