### ISSUE TITLE
No versions of 'ios-sdk-spm' match the requirement 1.4.9

### ISSUE THREAD

**Issue by bjford** [appspector/ios-sdk#28]
When trying to update 'ios-sdk-spm' package in Xcode I get the following error:

`Failed to resolve dependencies Dependencies could not be resolved because no versions of 'ios-sdk-spm' match the requirement 1.4.9..<2.0.0 and root depends on 'ios-sdk-spm' 1.4.9..<2.0.0.`

I believe this is because the `CFBundleVersion` value in the plist file is set to `1.4.8` for `AppSpectorSDK`, and `AppSpectorTVSDK`.

<img width="1152" alt="Screenshot 2024-03-20 at 14 25 40" src="https://github.com/appspector/ios-sdk/assets/9674571/34a6dedb-6607-4b36-8749-401d5a9876ab">
<img width="488" alt="Screenshot 2024-03-20 at 14 25 52" src="https://github.com/appspector/ios-sdk/assets/9674571/84f7cbae-9959-418a-ba29-74146faaa51a">

How to reproduce it:
* In Xcode, go to Package Dependencies and update 'ios-sdk-spm' to 1.4.9
* Download the [latest release source code](https://github.com/appspector/ios-sdk/releases/tag/1.4.9) , unzip AppSpectorSDK and inspect the plist file.

**Comment by deszip** [comment]
Hi @bjford , thanks for reporting this, we are aware of this issue and it will be fixed in the upcoming release in a day or two.
Sorry for inconvenience, as a workaround you can install 1.4.8 by setting an exact version.

**Comment by deszip** [comment]
Updated Package file in ios-sdk-spm repo but for some reason SPM stopped following links in it and just clones a repo with Package file...

Investigating it.

**Comment by deszip** [comment]
@emmanuelc-dk @bjford , v 1.4.10 of the SDK was just published. It has fixed Info.plist, should work fine.
Would be grrat if you can confirm that it works for you.

Thanks.

**Comment by deszip** [comment]
Awesome, thanks again for reporting. SPM is always a pain :)
