### ISSUE TITLE
v1.4.9 Missing path 'DebugSymbolsPath' 

### ISSUE THREAD

**Issue by emmanuelc-dk** [appspector/ios-sdk#29]
I updated to the latest version with SPM, and it cannot build, it fails with that error:

> Missing path (/Users/.../SourcePackages/artifacts/ios-sdk-spm/AppSpectorSDK/AppSpectorSDK.xcframework/ios-arm64_x86_64-simulator/dSYMs) from XCFramework 'AppSpectorSDK.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file

**Comment by deszip** [comment]
Hi @emmanuelc-dk, thanks for reporting, fix is on it's way. Will be available next week.

We already have issue for this: https://github.com/appspector/ios-sdk/issues/28
Please use it to track progress, I will close this one.
