### ISSUE TITLE
Failed to verify bitcode in submitting to App Store

### ISSUE THREAD

**Issue by harryworld** [appspector/ios-sdk#4]
I got this message while submitting to App Store
```
Failed to verify bitcode in AppSpectorSDK.framework/AppSpectorSDK:
error: Platform iOS is not supported
```

**Comment by deszip** [comment]
Hi @harryworld, would be great to have a screenshot of the error to understand on what step exactly did you get it. Do you use cocoapods to integrate AppSpector?

**Comment by deszip** [comment]
@harryworld Please check the latest SDK version, this should be already fixed. Feel free to reopen issue if problem still exists.

**Comment by frankus** [comment]
@deszip Apologies for the interruption, but would you be willing to share the steps you took to fix this? We have someone running into this exact (and seemingly quite rare) error message with our project.

**Comment by deszip** [comment]
Sure, in short, problem was that just enabling bitcode in your project settings affects only "archive" action and doesn't take any effect if you build framework with xcodebuild. Adding flag `OTHERCFLAGS=”-fembed-bitcode”` to `xcodebuild` options fixed the issue.

Some articles that were helpful:
[Static Libraries, Frameworks, and Bitcode](https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9)
[Embedded Bitcode](https://jonasdevlieghere.com/embedded-bitcode/)

Hope this helps.

**Comment by frankus** [comment]
Thanks so much for the help! FYI I believe our person has a different issue, where a framework built with Xcode 10.1 isn't archiving correctly for an app built in Xcode 9.4.1, but we're still investigating (they were able to get it to build by re-building the framework in Xcode 9.4.1).
